name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upd script version
        run: python ./release.py
      - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: GITHUB_ACTION
        author_email: zeroetime@163.com
        message: "(chore) update version"
        add: "main.js"
      - name: Prepare file
        run: mv main.js nflsoj-helper.min.user.js
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: nflsoj-helper.min.user.js